openapi: 3.0

info:
  title: Azuma Chat API
  description: API for the Azuma Chat service
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  version: 0.1.0

servers:
  - url: https://azuma.rmcprod.me/
    description: Azuma Instance hosted by RMC

paths:
  /api/:
    get:
      summary: API Version
      description: Returns the API version.
      responses:
        200:
          description: Successful request
          content:
            application/json:
              schema:
                type: object
                properties:
                  version:
                    type: string
              example:
                version: 0.1.0